/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/macbook.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/macbook.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.008]}>
        <mesh geometry={nodes.Keyboard_1.geometry} material={materials.Keycap} />
        <mesh geometry={nodes.Keyboard_2.geometry} material={materials['Keycap transparent plastic']} />
        <mesh geometry={nodes.Keyboard_3.geometry} material={materials['Anodized aluminum']} />
      </group>
      <group position={[0, -0.001, -0.121]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Lid_1.geometry} material={materials['Anodized aluminum']} />
        <mesh geometry={nodes.Lid_2.geometry} material={materials['Rubber gasket']} />
        <mesh geometry={nodes.Lid_3.geometry} material={materials['Plastic cover']} />
        <mesh geometry={nodes.Lid_4.geometry} material={materials.LCD} />
        <mesh geometry={nodes.Lid_5.geometry} material={materials['Black anodized aluminum']} />
        <mesh geometry={nodes.Lid_6.geometry} material={materials['Apple logo']} />
        <mesh geometry={nodes.Lid_7.geometry} material={materials['Display glass nanotexture']} />
        <mesh geometry={nodes.Lid_8.geometry} material={materials['Display frame']} />
        <mesh geometry={nodes.Lid_9.geometry} material={materials['Display glass']} />
        <mesh geometry={nodes.Lid_10.geometry} material={materials['Camera frame']} />
        <mesh geometry={nodes.Lid_11.geometry} material={materials['Camera lens']} />
      </group>
      <mesh geometry={nodes.Bottom_case_1.geometry} material={materials['Anodized aluminum']} />
      <mesh geometry={nodes.Bottom_case_2.geometry} material={materials['Rubber feet']} />
      <mesh geometry={nodes.Bottom_case_3.geometry} material={materials['Metal screw']} />
      <mesh geometry={nodes.Top_case_1.geometry} material={materials['Anodized aluminum']} />
      <mesh geometry={nodes.Top_case_2.geometry} material={materials['Gold pads']} />
      <mesh geometry={nodes.Top_case_3.geometry} material={materials['USBC port']} />
      <mesh geometry={nodes.Top_case_4.geometry} material={materials['Steel sheet']} />
      <mesh geometry={nodes.Top_case_5.geometry} material={materials.Keycap} />
      <mesh geometry={nodes.Top_case_6.geometry} material={materials['Jack port']} />
      <mesh geometry={nodes.Top_case_7.geometry} material={materials['Speaker mesh']} />
      <mesh geometry={nodes.Top_case_8.geometry} material={materials['Magsafe port']} />
      <mesh geometry={nodes.Top_case_9.geometry} material={materials['Black anodized aluminum']} />
      <mesh geometry={nodes.Trackpad_1.geometry} material={materials['Touchpad glass']} />
      <mesh geometry={nodes.Trackpad_2.geometry} material={materials['Touchpad tint']} />
    </group>
  )
}

useGLTF.preload('/macbook.glb')
