/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ipad.glb -o components/IpadModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ipad.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.abCKdjTFXRDygDg.geometry} material={materials.JGhcZOBeEEFTHKn} position={[0, 0.004, -0.002]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.AbYqbWxJIHjOZby.geometry} material={materials.EpOuwNoAjZWsZKD} position={[0, 0.003, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.alyIYLaJSyxzdjo.geometry} material={materials.kUWkRDVotcMnHsa} position={[-0.129, -0.002, -0.081]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.AuxUZFpIdyYVcpo.geometry} material={materials.HlUmGTGdgbnvPsa} position={[0, 0.004, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.aYGfoaryUOhgTnS.geometry} material={materials.zCUrKvqTeumKwRd} position={[0.135, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.BhdBOkQlZaHDoTI.geometry} material={materials.zuOGnslJhlJpvBY} position={[-0.126, -0.003, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.BmDZUOLgRVavGIP.geometry} material={materials.INAgtdCGscvtqIb} position={[-0.009, 0.003, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.CvToSjLIImJXFhl.geometry} material={materials.zCUrKvqTeumKwRd} position={[0.138, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.eYyEVqzuBtjteIL.geometry} material={materials.EpOuwNoAjZWsZKD} position={[0.136, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.fbKTxlqodhqsaMX.geometry} material={materials.ObnnNhDMEKJGYGc} position={[0.009, 0.004, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.FiSxQFtcGwcRlhx.geometry} material={materials.EpOuwNoAjZWsZKD} position={[-0.126, -0.003, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.forEYBSDPZlTPjB.geometry} material={materials.kUWkRDVotcMnHsa} position={[-0.114, -0.002, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.hmueEDnpjMcGMDz.geometry} material={materials.INAgtdCGscvtqIb} position={[-0.126, -0.002, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.hoqhCUbvqDNHqRQ.geometry} material={materials.zCUrKvqTeumKwRd} position={[0.137, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.hpmcIBmvWpyGHCe.geometry} material={materials.LmsMoHQNffKUBTk} position={[0.111, -0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.iBeJOrSUxnhIKau.geometry} material={materials.VHiYeyhfwJCxecr} position={[0.128, -0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.IilirTaurautXUM.geometry} material={materials.GGmNvstEGFjWJgL} position={[-0.126, -0.003, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.JGCbxCvPCDUDNDn.geometry} material={materials.ObnnNhDMEKJGYGc} position={[0, 0.004, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.jgPRgPdpKSiOXLh.geometry} material={materials.EpOuwNoAjZWsZKD} position={[-0.015, 0.004, -0.03]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.jSATzURBcTcYgwk.geometry} material={materials.GfvpWvxgaKYWFyg} position={[0.137, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.KAUAFnASbDDqbjr.geometry} material={materials.GGmNvstEGFjWJgL} position={[-0.009, 0.003, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.KEbVxBONOCIIMlV.geometry} material={materials.sbwzFjTAKUIwznL} position={[-0.12, -0.002, -0.081]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.KIKPIQftEQLSIGR.geometry} material={materials.ObnnNhDMEKJGYGc} position={[-0.011, 0.004, -0.042]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.LfbvDayYmwCLGgH.geometry} material={materials.eUutxxUdCpSsNmn} position={[-0.005, 0.004, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.LiBWsJueARwHeyy.geometry} material={materials.EpOuwNoAjZWsZKD} position={[-0.12, -0.002, -0.088]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.lZqTYwxpqlcavHT.geometry} material={materials.GfvpWvxgaKYWFyg} position={[-0.126, -0.003, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.McvRagXjmFhgQdO.geometry} material={materials.SAojaDrNKuRjUfl} position={[-0.014, 0.001, -0.021]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.MSiFPAFArNdbWRR.geometry} material={materials.ALwGWlgsdcFeIUW} position={[0.136, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.nTwZIAwkagNFGnY.geometry} material={materials.bMbvkgDjFaRXBwT} position={[-0.131, 0, 0.001]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.nvUUcAsUXWUkLSN.geometry} material={materials.WmIWTCLERDcqxSX} position={[0.128, -0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.NyGNnOKIVWPDXax.geometry} material={materials.ALwGWlgsdcFeIUW} position={[-0.12, -0.002, -0.081]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.OGSRAhdSqtkjQMb.geometry} material={materials.IHWKjkrmiwbOFTH} position={[0, 0.001, -0.002]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.qpCZMHZiiKuzTcT.geometry} material={materials.IMOWJWdEXKJRkmm} position={[-0.063, 0.001, -0.108]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.rFBGASmDBnpjGSc.geometry} material={materials.zuOGnslJhlJpvBY} position={[-0.009, 0.004, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.rQTOHXsvleKeWwr.geometry} material={materials.zhkMyvjxXbwgJAI} position={[-0.126, -0.002, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.RTKWTMHQzhACFeV.geometry} material={materials.bMbvkgDjFaRXBwT} position={[0.128, -0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.rYYeUMPiMwFRHIG.geometry} material={materials.EpOuwNoAjZWsZKD} position={[-0.126, 0.002, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.TIaOxogwgmXIHqv.geometry} material={materials.zCUrKvqTeumKwRd} position={[0.134, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.TvCCuUJvayYeyRp.geometry} material={materials.bMbvkgDjFaRXBwT} position={[0, 0.001, -0.108]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.uuuokMkIpLSMAUC.geometry} material={materials.GfvpWvxgaKYWFyg} position={[0.137, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.UVpecKJGwemnicG.geometry} material={materials.INAgtdCGscvtqIb} position={[-0.126, -0.002, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.VDrxmwCKuMJbOrN.geometry} material={materials.GfvpWvxgaKYWFyg} position={[0.136, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.viFxqLrOsGXiEnE.geometry} material={materials.zhkMyvjxXbwgJAI} position={[-0.009, 0.003, -0.103]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.wTXUGlwJUSOfxZY.geometry} material={materials.zCUrKvqTeumKwRd} position={[0.137, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.WWrgLTyPTAXTjUV.geometry} material={materials.euSZRXUQbKsAaPS} position={[-0.025, 0, -0.022]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.xfkAjFnAOwFauIm.geometry} material={materials.IyNcZeQAXJlnfTb} position={[-0.003, -0.001, 0.001]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.XtUsEXbIIYkfVAu.geometry} material={materials.xUNvBRVUcBVKMpV} position={[0.128, -0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.xyobRhOPEwyWxaY.geometry} material={materials.eUutxxUdCpSsNmn} position={[-0.136, 0.004, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.yfRfuoEFNIcZGev.geometry} material={materials.pZEJEUWlAIlYurO} position={[-0.12, -0.003, -0.081]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.yJwCklIOhimiTwo.geometry} material={materials.GfvpWvxgaKYWFyg} position={[0.134, 0.001, 0]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.YNxUkobHtiPdNCm.geometry} material={materials.EpOuwNoAjZWsZKD} position={[-0.004, 0.001, -0.014]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.ZqiJcXiEeUXUJtw.geometry} material={materials.zhkMyvjxXbwgJAI} position={[-0.126, -0.002, -0.094]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
      <mesh geometry={nodes.zzxkxqJBrKgpwhU.geometry} material={materials.RRggASOdsjdJMgp} position={[-0.113, -0.003, -0.081]} rotation={[Math.PI / 6, 0, Math.PI / 2]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/ipad.glb')
